DELETE http://localhost:3001/api/blogs/63e65939ab746638317005e6
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBldHJhLWFsYWhhcmp1bGEiLCJpZCI6IjYzZTY0OWQ1ZTJkZTBhNjQ4ZTcwZmMzYyIsImlhdCI6MTY3NjAzODg1MiwiZXhwIjoxNjc2MDQyNDUyfQ.aaunXLyoHNLNQbrKdQ5uodM1CZL3zJf8h6_bL2hpX8U